namespace Helpers.Localization;

public static class LocalizationKeys
{
    public const string DataNotFound = nameof(DataNotFound);
    public const string Name = nameof(Name);
    public const string FirstName = nameof(FirstName);
    public const string LastName = nameof(LastName);
    public const string Email = nameof(Email);
    public const string Password = nameof(Password);
    public const string ConfirmPassword = nameof(ConfirmPassword);
    public const string PasswordsNotMatch = nameof(PasswordsNotMatch);
    public const string MissingApiKey = nameof(MissingApiKey);
    public const string InvalidApiKey = nameof(InvalidApiKey);
    public const string AccountConfirmation = nameof(AccountConfirmation);
    public const string InvalidMobileNumber = nameof(InvalidMobileNumber);
    public const string CountryCode = nameof(CountryCode);
    public const string Token = nameof(Token);
    public const string DuplicateEmail = nameof(DuplicateEmail);
    public const string DuplicateUserName = nameof(DuplicateUserName);
    public const string InvalidEmail = nameof(InvalidEmail);
    public const string DuplicateRoleName = nameof(DuplicateRoleName);
    public const string InvalidRoleName = nameof(InvalidRoleName);
    public const string InvalidToken = nameof(InvalidToken);
    public const string InvalidUserName = nameof(InvalidUserName);
    public const string LoginAlreadyAssociated = nameof(LoginAlreadyAssociated);
    public const string PasswordMismatch = nameof(PasswordMismatch);
    public const string PasswordRequiresDigit = nameof(PasswordRequiresDigit);
    public const string PasswordRequiresLower = nameof(PasswordRequiresLower);
    public const string PasswordRequiresNonAlphanumeric = nameof(PasswordRequiresNonAlphanumeric);
    public const string PasswordRequiresUniqueChars = nameof(PasswordRequiresUniqueChars);
    public const string PasswordRequiresUpper = nameof(PasswordRequiresUpper);
    public const string PasswordTooShort = nameof(PasswordTooShort);
    public const string UserAlreadyHasPassword = nameof(UserAlreadyHasPassword);
    public const string UserAlreadyInRole = nameof(UserAlreadyInRole);
    public const string UserNotInRole = nameof(UserNotInRole);
    public const string UserLockoutNotEnabled = nameof(UserLockoutNotEnabled);
    public const string RecoveryCodeRedemptionFailed = nameof(RecoveryCodeRedemptionFailed);
    public const string ConcurrencyFailure = nameof(ConcurrencyFailure);
    public const string DefaultIdentityError = nameof(DefaultIdentityError);
    public const string ResetPassword = nameof(ResetPassword);
    public const string InvalidCredentials = nameof(InvalidCredentials);
    public const string EmailNotConfirmed = nameof(EmailNotConfirmed);
    public const string Username = nameof(Username);
    public const string UserNotFound = nameof(UserNotFound);
    public const string FirstNameRequired = nameof(FirstNameRequired);
    public const string UserNameRequired = nameof(UserNameRequired);
    public const string EmailRequired = nameof(EmailRequired);
    public const string DeviceModel = nameof(DeviceModel);
    public const string DeviceToken = nameof(DeviceToken);
    public const string NotValidFileSize = nameof(NotValidFileSize);
    public const string NotValidFileType = nameof(NotValidFileType);
    public const string File = nameof(File);
    public const string OperationDoneSuccessfully = nameof(OperationDoneSuccessfully);
    public const string RoleName = nameof(RoleName);
    public const string Permissions = nameof(Permissions);
    public const string DuplicateRole = nameof(DuplicateRole);
}
